services:
  accounts:
    image: "bhavesh16281/accounts:011"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - "banking-network"
  loans:
    image: "bhavesh16281/loans:011"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - "banking-network"
  cards:
    image: "bhavesh16281/cards:011"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - "banking-network"
networks:
    banking-network:
        driver: "bridge"
